// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dctkidlofkgiiddfeehn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdGtpZGxvZmtnaWlkZGZlZWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDAwODAsImV4cCI6MjA1MzM3NjA4MH0.PflWLWfHFv6ygdhQPpc5xflSfSVpJmFP3M5Lrm9m8ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);